(in-package #:agni)


(defun tar-bytes-name (file))
(defun tar-bytes-mode (file))
(defun tar-bytes-uid (file))
(defun tar-bytes-gid (file))
(defun tar-bytes-size (file))
(defun tar-bytes-mtime (file))
(defun tar-bytes-chksum (file))
(defun tar-bytes-typeflag (file))
(defun tar-bytes-linkname (file))
(defun tar-bytes-magic (file))
(defun tar-bytes-version (file))
(defun tar-bytes-uname (file))
(defun tar-bytes-gname (file))
(defun tar-bytes-devmajor (file))
(defun tar-bytes-devminor (file))
(defun tar-bytes-prefix (file))
(defun tar-bytes-content (file))
