(in-package #:agni)


(defconstant +name-offset+ 0)
(defconstant +mode-offset+ 100)
(defconstant +uid-offset+ 108)
(defconstant +gid-offset+ 116)
(defconstant +size+ 124)
(defconstant +mtime+ 136)
(defconstant +chksum+ 148)
(defconstant +typeflag+ 156)
(defconstant +linkname+ 157)
(defconstant +magic+ 257)
(defconstant +version+ 263)
(defconstant +uname+ 265)
(defconstant +gname+ 297)
(defconstant +devmajor+ 329)
(defconstant +devminor+ 337)
(defconstant +prefix+ 345)

(defmethod tar-bytes-name ((f file) &key)
  (vector-add (string-to-bytes (tar-path f)) (tar-bytes-headers f) +name-offset+))

(defmethod tar-bytes-mode ((f file) &key)
  (vector-add (string-to-bytes (format nil "~O" (mode f)))
              (tar-bytes-headers f)
              +mode-offset+))

(defmethod tar-bytes-uid ((f file) &key))
(defmethod tar-bytes-gid ((f file) &key))
(defmethod tar-bytes-size ((f file) &key))
(defmethod tar-bytes-mtime ((f file) &key))
(defmethod tar-bytes-chksum ((f file) &key))
(defmethod tar-bytes-typeflag ((f file) &key))
(defmethod tar-bytes-linkname ((f file) &key))
(defmethod tar-bytes-magic ((f file) &key))
(defmethod tar-bytes-version ((f file) &key))
(defmethod tar-bytes-uname ((f file) &key))
(defmethod tar-bytes-gname ((f file) &key))
(defmethod tar-bytes-devmajor ((f file) &key))
(defmethod tar-bytes-devminor ((f file) &key))
(defmethod tar-bytes-prefix ((f file) &key))
(defmethod tar-bytes-calculate-checksum ((f file) &key))
(defmethod tar-bytes-content ((f file) &key))
