(in-package #:agni)


(defmethod tar-bytes-name ((f file) &key)
  (vector-add (mapcar #'char-code (coerce (tar-path f) 'list)) (tar-bytes-headers f) 0))

(defmethod tar-bytes-mode ((f file) &key))
(defmethod tar-bytes-uid ((f file) &key))
(defmethod tar-bytes-gid ((f file) &key))
(defmethod tar-bytes-size ((f file) &key))
(defmethod tar-bytes-mtime ((f file) &key))
(defmethod tar-bytes-chksum ((f file) &key))
(defmethod tar-bytes-typeflag ((f file) &key))
(defmethod tar-bytes-linkname ((f file) &key))
(defmethod tar-bytes-magic ((f file) &key))
(defmethod tar-bytes-version ((f file) &key))
(defmethod tar-bytes-uname ((f file) &key))
(defmethod tar-bytes-gname ((f file) &key))
(defmethod tar-bytes-devmajor ((f file) &key))
(defmethod tar-bytes-devminor ((f file) &key))
(defmethod tar-bytes-prefix ((f file) &key))
(defmethod tar-bytes-calculate-checksum ((f file) &key))
(defmethod tar-bytes-content ((f file) &key))
